//! Rust-via-midenc specific support for the Miden tracer.
//!
//! When Rust code is compiled to Miden assembly via the `midenc` compiler,
//! the `AssemblyOp::location()` contains a `Location` whose `path` field
//! points to `.rs` source files rather than `.masm` files. The byte offsets
//! in the `Location` correspond to positions within those Rust source files.
//!
//! This module provides:
//! - [`SourceLanguage`]: detection of source language from file extensions
//! - [`RustSourceResolver`]: resolution of Rust source file paths
//! - [`is_synthetic_location`]: filtering of compiler-generated synthetic ops

use std::path::{Path, PathBuf};

use miden_core::debuginfo::Location;

/// The source language detected from a file extension.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SourceLanguage {
    /// Miden assembly (`.masm`)
    Masm,
    /// Rust compiled via midenc (`.rs`)
    Rust,
    /// Unknown or unsupported source language
    Unknown,
}

impl SourceLanguage {
    /// Detect the source language from a file path or URI string.
    ///
    /// Examines the file extension to determine the language:
    /// - `.masm` -> `Masm`
    /// - `.rs` -> `Rust`
    /// - anything else -> `Unknown`
    pub fn from_path(path: &str) -> Self {
        if path.ends_with(".masm") {
            SourceLanguage::Masm
        } else if path.ends_with(".rs") {
            SourceLanguage::Rust
        } else {
            SourceLanguage::Unknown
        }
    }
}

/// Check whether a `Location` is synthetic (compiler-generated with no
/// meaningful source mapping).
///
/// A location is considered synthetic when:
/// - Its `path` is empty
/// - Its byte range is zero-length at offset 0 (start == end == 0)
///
/// Synthetic locations are generated by the midenc compiler for operations
/// that have no direct correspondence to user-written source code.
pub fn is_synthetic_location(loc: &Location) -> bool {
    if loc.path.is_empty() {
        return true;
    }
    let start: u32 = loc.start.into();
    let end: u32 = loc.end.into();
    start == 0 && end == 0 && loc.path.contains("<synthetic>")
}

/// Resolves Rust source files referenced by midenc-compiled programs.
///
/// When midenc compiles Rust code, the `Location.path` field typically
/// contains an absolute path to the `.rs` source file as it existed
/// during compilation. This resolver attempts to find the actual file
/// on disk, searching through a set of configured directories if the
/// original path is not found.
pub struct RustSourceResolver {
    /// Directories to search for source files.
    search_dirs: Vec<PathBuf>,
}

impl RustSourceResolver {
    /// Create a new resolver that searches the given directories.
    pub fn new(search_dirs: Vec<PathBuf>) -> Self {
        Self { search_dirs }
    }

    /// Resolve a URI from a midenc `Location.path` to an actual file path.
    ///
    /// Resolution strategy:
    /// 1. If the URI is an absolute path that exists, return it directly.
    /// 2. Otherwise, extract the filename and search for it in the
    ///    configured search directories (non-recursively).
    ///
    /// Returns `None` if the file cannot be found.
    pub fn resolve(&self, uri: &str) -> Option<PathBuf> {
        // Try the URI as an absolute path first.
        let as_path = Path::new(uri);
        if as_path.is_absolute() && as_path.exists() {
            return Some(as_path.to_path_buf());
        }

        // Extract the filename and search in configured directories.
        let filename = Path::new(uri).file_name()?;
        for dir in &self.search_dirs {
            let candidate = dir.join(filename);
            if candidate.exists() {
                return Some(candidate);
            }
        }

        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_source_language_detection() {
        assert_eq!(SourceLanguage::from_path("compute.masm"), SourceLanguage::Masm);
        assert_eq!(SourceLanguage::from_path("/path/to/lib.rs"), SourceLanguage::Rust);
        assert_eq!(SourceLanguage::from_path("program.move"), SourceLanguage::Unknown);
        assert_eq!(SourceLanguage::from_path(""), SourceLanguage::Unknown);
        assert_eq!(
            SourceLanguage::from_path("/home/user/project/src/main.rs"),
            SourceLanguage::Rust
        );
        assert_eq!(
            SourceLanguage::from_path("test-programs/masm/compute.masm"),
            SourceLanguage::Masm
        );
    }
}
